### ISSUE TITLE
Default mesage doesnt do replace for {0} if the "param" is 0

### ISSUE THREAD

**Issue by projecteon** [Knockout-Contrib/Knockout-Validation#557] opened 2015-04-27 10:23 UTC
I wanted a greater than validation and hooked it up as follows:
self.number = ko.observable().extend({ greaterThan: 0 });

With:
ko.validation.rules['greaterThan'] = {
	validator: function (val, min) {
		return val> min;
	},
	message: 'The field must be greater than {0}'
};

Problem is that the replacement for error message does not happen.
The isArray function fails when "param" is 0 in formatMessage function.

http://jsfiddle.net/c3j5mrrd/2/

**Comment by crissdev** [comment] 2015-04-27 10:36
Duplicate of #547

**Closed by crissdev** 2015-04-27 10:36 UTC
Labels: duplicate

**Comment by crissdev** [comment] 2015-04-27 10:39
Consider using the the [v2.1.0](https://github.com/Knockout-Contrib/Knockout-Validation/tree/v2.1.0) branch until a new release is available. Or you can manually apply the patch if you use a local version of the library.
