### ISSUE TITLE
Async validation message not displaying even when callback is invoked

### ISSUE THREAD

**Issue by MatthewLymer** [Knockout-Contrib/Knockout-Validation#552] opened 2015-03-09 20:37 UTC
This may be my misunderstanding of how async validation works, so please bear with me.

	ko.observable('').extend({
		validation: {
			async: true,
			validator: function (val, params, callback) {
				console.log('val: ' + val);
				callback(false);
			},
			message: "Your field is invalid"
		}        
	});

Even though the validation function is being invoked, and `callback` is being passed `false`, I do not see any validation message.

The synchronous version, however, displays the message when the value is changed.

	ko.observable('').extend({
		validation: {
			async: false,
			validator: function (val, params) {
				console.log('val: ' + val);
				return false;
			},
			message: "Your field is invalid"
		}        
	});

Am I supposed to output the error message manually or some other step I forgot to do?

A jsfiddle with the previous example can be found: http://jsfiddle.net/whvse6qw/4/

**Comment by crissdev** [comment] 2015-03-09 23:28
The problem is that your callback returns early. A simple `setTimeout` will fix your issue - see #341. The fix is available in master branch - 52daa1050ca61b83a0c38eebdafe19f1f17465b1

Updated example http://jsfiddle.net/whvse6qw/5/

---
Marking this issue as duplicate of #341

**Closed by crissdev** 2015-03-09 23:28 UTC
Labels: duplicate

**Comment by MatthewLymer** [comment] 2015-03-09 23:36
This solves the problem, thank you for your support Cristian
