### ISSUE TITLE
knockout validation group css applies only first time error happends

### ISSUE THREAD

**Issue by PedroLV** [Knockout-Contrib/Knockout-Validation#608] opened 2016-03-11 12:27 UTC
I've a knockout model with an array of objects into a validation group.
I want to validate existing arrayitems before add a new one into the observableArray, and it's works, but only the first time error occurs. In next error cases, validationgroup shows "1 error or whatever" errors but CSS is not applied to the textbox. ¿Why CSS is applied only first time error happends?

I've a fiddle to reproduce de issue. Steps 

- 1- press add data button 
- 2- leave the textbox without value and press Add data again. Everything is ok, error is showing and css is applied 
- 3- fill textbox with any value 
- 4- press Add data and let the new textbox empty. 
- 5- press Add data again. wow!! Why CSS is not applied????

https://fiddle.jshell.net/srg25j3b/19/

Thanks all.

**Comment by crissdev** [comment] 2016-03-11 15:35
Thanks for a great description. This has to do with the `parseInputAttributes` - see related issue #520 
A quick fix is to make the observable validatable - https://fiddle.jshell.net/srg25j3b/21/ (line 34)

---
Duplicate of #520

**Closed by crissdev** 2016-03-11 15:35 UTC
Labels: duplicate
