### ISSUE TITLE
How to put foucs on which is a requied field

### ISSUE THREAD

**Issue by usamamashkoor** [Knockout-Contrib/Knockout-Validation#582] opened 2015-09-14 07:32 UTC
Hi How are you..
i am new to knockout 
i have been studying you knockout library it is really awsome thanks for this man.
but i have a problem i was hopping that you can help me on it 
i have required validation on two fields
projectName: ko.observable('').extend({ required: true }),
projectDesignation: ko.observable('').extend({ required: true }),
what i want is to do that i want to show focus on the field which the user left empty if it is first field then show focus on the first filed if the second field is empty then show focus on the second field 
Thanks in advance

**Comment by crissdev** [comment] 2015-09-14 19:22
Hey @usamamashkoor. Thanks for your nice words.
This feature isn't available at the moment - you might want to try a custom binding or read the information available in #164
---
Duplicate of #164

**Closed** 2015-09-14 19:22 UTC
